import { hashSync } from "bcryptjs";

import type {
    MenuGroupConfig,
    ResourceConfig,
    ResourceField,
} from "../types/resource";

const BOOLEAN_OPTIONS = [
  { label: "是", value: 1 },
  { label: "否", value: 0 },
];

const STATUS_OPTIONS = [
  { label: "启用", value: 1 },
  { label: "禁用", value: 0 },
];

const GENDER_OPTIONS = [
  { label: "未知", value: 0 },
  { label: "男", value: 1 },
  { label: "女", value: 2 },
];

const USER_TYPE_OPTIONS = [
  { label: "普通用户", value: 1 },
  { label: "管理员", value: 2 },
];

const JUMP_TYPE_OPTIONS = [
  { label: "无跳转", value: 1 },
  { label: "内容详情", value: 2 },
  { label: "分类页", value: 3 },
  { label: "外部链接", value: 4 },
];

const CONTENT_TYPE_OPTIONS = [
  { label: "电影", value: 1 },
  { label: "电视剧", value: 2 },
  { label: "动漫", value: 3 },
  { label: "综艺", value: 4 },
  { label: "短剧", value: 5 },
];

const PERSON_TYPE_OPTIONS = [
  { label: "演员", value: 1 },
  { label: "导演", value: 2 },
  { label: "编剧", value: 3 },
  { label: "配音", value: 4 },
  { label: "其他", value: 5 },
];

const JOB_TYPE_OPTIONS = [
  { label: "演员", value: 1 },
  { label: "导演", value: 2 },
  { label: "编剧", value: 3 },
  { label: "配音", value: 4 },
  { label: "其他", value: 5 },
];

const PERM_TYPE_OPTIONS = [
  { label: "菜单", value: 1 },
  { label: "按钮", value: 2 },
  { label: "接口", value: 3 },
];

const MESSAGE_TYPE_OPTIONS = [
  { label: "文本", value: 1 },
  { label: "图片", value: 2 },
  { label: "系统通知", value: 3 },
  { label: "业务提醒", value: 4 },
];

const COMMON_FIELDS: Record<string, ResourceField> = {
  id: {
    name: "id",
    label: "ID",
    type: "number",
    list: true,
    form: false,
    width: 90,
  },
  status: {
    name: "status",
    label: "状态",
    type: "switch",
    list: true,
    form: true,
    options: STATUS_OPTIONS,
  },
  sortOrder: {
    name: "sortOrder",
    label: "排序值",
    type: "number",
    list: true,
    form: true,
  },
  remark: {
    name: "remark",
    label: "备注",
    type: "textarea",
    span: 2,
    list: false,
    form: true,
  },
  createTime: {
    name: "createTime",
    label: "创建时间",
    type: "datetime",
    list: true,
    form: false,
    width: 180,
  },
  updateTime: {
    name: "updateTime",
    label: "更新时间",
    type: "datetime",
    list: true,
    form: false,
    width: 180,
  },
};

export const resourceConfigs: Record<string, ResourceConfig> = {
  "sys-user": {
    key: "sys-user",
    title: "系统用户",
    apiPath: "/api/system/users",
    description: "管理后台登录用户、权限状态与个人资料。",
    searchableFields: ["username", "email", "phone", "nickname"],
    beforeSubmit: (payload, editing) => {
      const nextPayload = { ...payload };
      const rawPassword = String(nextPayload.password ?? "").trim();

      if (!editing && !rawPassword) {
        throw new Error("新建系统用户时必须填写登录密码");
      }

      if (rawPassword) {
        nextPayload.passwordHash = hashSync(rawPassword, 10);
      }

      delete nextPayload.password;
      return nextPayload;
    },
    fields: [
      COMMON_FIELDS.id,
      {
        name: "username",
        label: "用户名",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      { name: "email", label: "邮箱", type: "text", list: true, form: true },
      { name: "phone", label: "手机号", type: "text", list: true, form: true },
      {
        name: "password",
        label: "登录密码",
        type: "password",
        required: false,
        list: false,
        form: true,
        span: 2,
        placeholder: "留空表示不修改密码",
      },
      { name: "nickname", label: "昵称", type: "text", list: true, form: true },
      {
        name: "avatarUrl",
        label: "头像地址",
        type: "url",
        list: false,
        form: true,
        span: 2,
      },
      {
        name: "signature",
        label: "个人签名",
        type: "textarea",
        list: false,
        form: true,
        span: 2,
      },
      {
        name: "gender",
        label: "性别",
        type: "select",
        list: true,
        form: true,
        options: GENDER_OPTIONS,
      },
      {
        name: "userType",
        label: "用户类型",
        type: "select",
        list: true,
        form: true,
        options: USER_TYPE_OPTIONS,
      },
      {
        name: "vipLevel",
        label: "会员等级",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "vipExpireTime",
        label: "会员到期时间",
        type: "datetime",
        list: true,
        form: true,
      },
      {
        name: "coinBalance",
        label: "硬币余额",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "bcoinBalance",
        label: "B币余额",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "level",
        label: "用户等级",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "lastLoginTime",
        label: "最后登录时间",
        type: "datetime",
        list: true,
        form: false,
      },
      {
        name: "lastLoginIp",
        label: "最后登录IP",
        type: "text",
        list: true,
        form: false,
      },
      COMMON_FIELDS.status,
      COMMON_FIELDS.remark,
      COMMON_FIELDS.createTime,
      COMMON_FIELDS.updateTime,
    ],
  },
  "sys-role": {
    key: "sys-role",
    title: "角色管理",
    apiPath: "/api/system/roles",
    description: "维护后台角色编码、名称和启用状态。",
    searchableFields: ["roleCode", "roleName", "remark"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "roleCode",
        label: "角色编码",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      {
        name: "roleName",
        label: "角色名称",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      COMMON_FIELDS.status,
      COMMON_FIELDS.sortOrder,
      COMMON_FIELDS.remark,
      COMMON_FIELDS.createTime,
      COMMON_FIELDS.updateTime,
    ],
  },
  "sys-permission": {
    key: "sys-permission",
    title: "权限管理",
    apiPath: "/api/system/permissions",
    description: "配置菜单、按钮和接口权限。",
    searchableFields: [
      "permissionCode",
      "permissionName",
      "resourcePath",
      "remark",
    ],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "parentId",
        label: "父权限ID",
        type: "select",
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-permission",
          labelFields: ["permissionName", "permissionCode"],
        },
      },
      {
        name: "permissionCode",
        label: "权限编码",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      {
        name: "permissionName",
        label: "权限名称",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      {
        name: "permType",
        label: "权限类型",
        type: "select",
        list: true,
        form: true,
        options: PERM_TYPE_OPTIONS,
      },
      {
        name: "resourcePath",
        label: "资源路径",
        type: "text",
        list: true,
        form: true,
        span: 2,
      },
      COMMON_FIELDS.status,
      COMMON_FIELDS.sortOrder,
      COMMON_FIELDS.remark,
      COMMON_FIELDS.createTime,
      COMMON_FIELDS.updateTime,
    ],
  },
  "sys-user-role": {
    key: "sys-user-role",
    title: "用户角色关联",
    apiPath: "/api/system/user-roles",
    description: "维护用户与角色的绑定关系。",
    searchableFields: ["userId", "roleId"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "userId",
        label: "用户ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-user",
          labelFields: ["nickname", "username"],
        },
      },
      {
        name: "roleId",
        label: "角色ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-role",
          labelFields: ["roleName", "roleCode"],
        },
      },
      COMMON_FIELDS.createTime,
    ],
  },
  "sys-role-permission": {
    key: "sys-role-permission",
    title: "角色权限关联",
    apiPath: "/api/system/role-permissions",
    description: "维护角色与权限的映射关系。",
    searchableFields: ["roleId", "permissionId"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "roleId",
        label: "角色ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-role",
          labelFields: ["roleName", "roleCode"],
        },
      },
      {
        name: "permissionId",
        label: "权限ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-permission",
          labelFields: ["permissionName", "permissionCode"],
        },
      },
      COMMON_FIELDS.createTime,
    ],
  },
  "app-banner": {
    key: "app-banner",
    title: "轮播图管理",
    apiPath: "/api/home/banners",
    description: "管理首页轮播图、跳转目标与生效时间。",
    searchableFields: ["bannerTitle", "jumpTarget", "remark"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "bannerTitle",
        label: "轮播图标题",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      {
        name: "imageUrl",
        label: "图片地址",
        type: "image",
        required: true,
        list: true,
        form: true,
        span: 2,
      },
      {
        name: "jumpType",
        label: "跳转类型",
        type: "select",
        list: true,
        form: true,
        options: JUMP_TYPE_OPTIONS,
      },
      {
        name: "jumpTarget",
        label: "跳转目标",
        type: "text",
        list: true,
        form: true,
      },
      COMMON_FIELDS.sortOrder,
      COMMON_FIELDS.status,
      {
        name: "startTime",
        label: "开始展示时间",
        type: "datetime",
        list: true,
        form: true,
      },
      {
        name: "endTime",
        label: "结束展示时间",
        type: "datetime",
        list: true,
        form: true,
      },
      COMMON_FIELDS.remark,
      COMMON_FIELDS.createTime,
      COMMON_FIELDS.updateTime,
    ],
  },
  "app-category": {
    key: "app-category",
    title: "内容分类",
    apiPath: "/api/content/categories",
    description: "维护内容分类、父子层级和推荐状态。",
    searchableFields: ["categoryName", "categoryCode", "remark"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "parentId",
        label: "父分类ID",
        type: "select",
        list: true,
        form: true,
        relation: {
          resourceKey: "app-category",
          labelFields: ["categoryName", "categoryCode"],
        },
      },
      {
        name: "categoryName",
        label: "分类名称",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      {
        name: "categoryCode",
        label: "分类编码",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      {
        name: "iconUrl",
        label: "图标地址",
        type: "url",
        list: true,
        form: true,
      },
      {
        name: "coverUrl",
        label: "封面地址",
        type: "image",
        list: true,
        form: true,
      },
      COMMON_FIELDS.sortOrder,
      COMMON_FIELDS.status,
      {
        name: "isRecommend",
        label: "是否推荐",
        type: "switch",
        list: true,
        form: true,
        options: BOOLEAN_OPTIONS,
      },
      COMMON_FIELDS.remark,
      COMMON_FIELDS.createTime,
      COMMON_FIELDS.updateTime,
    ],
  },
  "app-media": {
    key: "app-media",
    title: "内容管理",
    apiPath: "/api/content/media",
    description: "管理影视内容、标签、评分和播放量。",
    searchableFields: ["mediaCode", "title", "subtitle", "tags", "director"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "categoryId",
        label: "主分类ID",
        type: "select",
        list: true,
        form: true,
        relation: {
          resourceKey: "app-category",
          labelFields: ["categoryName", "categoryCode"],
        },
      },
      {
        name: "mediaCode",
        label: "内容编码",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      {
        name: "title",
        label: "内容标题",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      {
        name: "subtitle",
        label: "副标题",
        type: "text",
        list: true,
        form: true,
      },
      {
        name: "coverUrl",
        label: "封面图地址",
        type: "image",
        list: true,
        form: true,
        span: 2,
      },
      {
        name: "posterUrl",
        label: "海报图地址",
        type: "image",
        list: true,
        form: true,
        span: 2,
      },
      {
        name: "contentType",
        label: "内容类型",
        type: "select",
        list: true,
        form: true,
        options: CONTENT_TYPE_OPTIONS,
      },
      { name: "region", label: "地区", type: "text", list: true, form: true },
      { name: "director", label: "导演", type: "text", list: true, form: true },
      {
        name: "briefIntro",
        label: "短简介",
        type: "textarea",
        list: false,
        form: true,
        span: 2,
      },
      {
        name: "detailIntro",
        label: "详细介绍",
        type: "textarea",
        list: false,
        form: true,
        span: 2,
      },
      {
        name: "tags",
        label: "标签",
        type: "text",
        list: true,
        form: true,
        span: 2,
      },
      {
        name: "releaseDate",
        label: "上线日期",
        type: "date",
        list: true,
        form: true,
      },
      {
        name: "totalEpisodes",
        label: "总集数",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "latestEpisodeNo",
        label: "最新集数",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "durationSeconds",
        label: "时长(秒)",
        type: "number",
        list: true,
        form: true,
      },
      { name: "score", label: "评分", type: "number", list: true, form: true },
      {
        name: "scoreCount",
        label: "评分人数",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "viewCount",
        label: "播放量",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "favoriteCount",
        label: "收藏量",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "commentCount",
        label: "评论量",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "isHot",
        label: "是否热门",
        type: "switch",
        list: true,
        form: true,
        options: BOOLEAN_OPTIONS,
      },
      {
        name: "isRecommend",
        label: "是否推荐",
        type: "switch",
        list: true,
        form: true,
        options: BOOLEAN_OPTIONS,
      },
      COMMON_FIELDS.status,
      COMMON_FIELDS.sortOrder,
      {
        name: "createdBy",
        label: "创建人ID",
        type: "select",
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-user",
          labelFields: ["nickname", "username"],
        },
      },
      {
        name: "updatedBy",
        label: "更新人ID",
        type: "select",
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-user",
          labelFields: ["nickname", "username"],
        },
      },
      COMMON_FIELDS.remark,
      COMMON_FIELDS.createTime,
      COMMON_FIELDS.updateTime,
    ],
  },
  "app-media-episode": {
    key: "app-media-episode",
    title: "内容分集",
    apiPath: "/api/content/episodes",
    description: "维护每个内容的分集播放地址和状态。",
    searchableFields: ["episodeTitle", "playUrl", "mediaId"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "mediaId",
        label: "内容ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "app-media",
          labelFields: ["title", "mediaCode"],
        },
      },
      {
        name: "episodeNo",
        label: "集数编号",
        type: "number",
        required: true,
        list: true,
        form: true,
      },
      {
        name: "episodeTitle",
        label: "分集标题",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      {
        name: "playUrl",
        label: "播放地址",
        type: "video",
        required: true,
        list: true,
        form: true,
        span: 2,
      },
      {
        name: "durationSeconds",
        label: "时长(秒)",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "isFree",
        label: "是否免费",
        type: "switch",
        list: true,
        form: true,
        options: BOOLEAN_OPTIONS,
      },
      COMMON_FIELDS.status,
      COMMON_FIELDS.sortOrder,
      COMMON_FIELDS.remark,
      COMMON_FIELDS.createTime,
      COMMON_FIELDS.updateTime,
    ],
  },
  "app-media-person-rel": {
    key: "app-media-person-rel",
    title: "内容人物关联",
    apiPath: "/api/content/media-person-relations",
    description: "维护内容和人物之间的出演、导演等关联。",
    searchableFields: ["mediaId", "personId", "characterName"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "mediaId",
        label: "内容ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "app-media",
          labelFields: ["title", "mediaCode"],
        },
      },
      {
        name: "personId",
        label: "人物ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "app-person",
          labelFields: ["personName", "personType"],
        },
      },
      {
        name: "jobType",
        label: "关联身份",
        type: "select",
        list: true,
        form: true,
        options: JOB_TYPE_OPTIONS,
      },
      {
        name: "characterName",
        label: "角色名",
        type: "text",
        list: true,
        form: true,
      },
      COMMON_FIELDS.sortOrder,
      COMMON_FIELDS.createTime,
    ],
  },
  "app-person": {
    key: "app-person",
    title: "人物管理",
    apiPath: "/api/content/persons",
    description: "维护演员、导演、编剧、配音等人物信息。",
    searchableFields: ["personName", "originPlace", "bio"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "personName",
        label: "人员名称",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      {
        name: "personType",
        label: "人员类型",
        type: "select",
        list: true,
        form: true,
        options: PERSON_TYPE_OPTIONS,
      },
      {
        name: "avatarUrl",
        label: "头像地址",
        type: "image",
        list: true,
        form: true,
      },
      {
        name: "gender",
        label: "性别",
        type: "select",
        list: true,
        form: true,
        options: GENDER_OPTIONS,
      },
      {
        name: "birthday",
        label: "出生日期",
        type: "date",
        list: true,
        form: true,
      },
      {
        name: "originPlace",
        label: "籍贯或地区",
        type: "text",
        list: true,
        form: true,
      },
      {
        name: "bio",
        label: "人物简介",
        type: "textarea",
        list: false,
        form: true,
        span: 2,
      },
      COMMON_FIELDS.status,
      COMMON_FIELDS.remark,
      COMMON_FIELDS.createTime,
      COMMON_FIELDS.updateTime,
    ],
  },
  "app-comment": {
    key: "app-comment",
    title: "评论管理",
    apiPath: "/api/social/comments",
    description: "管理内容评论、回复关系和审核状态。",
    searchableFields: ["mediaId", "userId", "content"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "mediaId",
        label: "内容ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "app-media",
          labelFields: ["title", "mediaCode"],
        },
      },
      {
        name: "userId",
        label: "用户ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-user",
          labelFields: ["nickname", "username"],
        },
      },
      {
        name: "parentId",
        label: "父评论ID",
        type: "select",
        list: true,
        form: true,
        relation: {
          resourceKey: "app-comment",
          labelFields: ["content"],
        },
      },
      {
        name: "content",
        label: "评论内容",
        type: "textarea",
        required: true,
        list: true,
        form: true,
        span: 2,
      },
      {
        name: "likeCount",
        label: "点赞数",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "replyCount",
        label: "回复数",
        type: "number",
        list: true,
        form: true,
      },
      COMMON_FIELDS.status,
      COMMON_FIELDS.remark,
      COMMON_FIELDS.createTime,
      COMMON_FIELDS.updateTime,
    ],
  },
  "app-favorite": {
    key: "app-favorite",
    title: "收藏记录",
    apiPath: "/api/social/favorites",
    description: "查看用户收藏与内容之间的绑定记录。",
    searchableFields: ["userId", "mediaId"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "userId",
        label: "用户ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-user",
          labelFields: ["nickname", "username"],
        },
      },
      {
        name: "mediaId",
        label: "内容ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "app-media",
          labelFields: ["title", "mediaCode"],
        },
      },
      COMMON_FIELDS.createTime,
    ],
  },
  "app-follow": {
    key: "app-follow",
    title: "关注关系",
    apiPath: "/api/social/follows",
    description: "查看粉丝与被关注者之间的关注关系。",
    searchableFields: ["followerUserId", "followeeUserId"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "followerUserId",
        label: "关注者用户ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-user",
          labelFields: ["nickname", "username"],
        },
      },
      {
        name: "followeeUserId",
        label: "被关注者用户ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-user",
          labelFields: ["nickname", "username"],
        },
      },
      COMMON_FIELDS.createTime,
    ],
  },
  "app-watch-history": {
    key: "app-watch-history",
    title: "观看历史",
    apiPath: "/api/social/watch-histories",
    description: "查看用户播放进度、是否看完和最近观看时间。",
    searchableFields: ["userId", "mediaId", "episodeId"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "userId",
        label: "用户ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-user",
          labelFields: ["nickname", "username"],
        },
      },
      {
        name: "mediaId",
        label: "内容ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "app-media",
          labelFields: ["title", "mediaCode"],
        },
      },
      {
        name: "episodeId",
        label: "分集ID",
        type: "select",
        list: true,
        form: true,
        relation: {
          resourceKey: "app-media-episode",
          labelFields: ["episodeTitle", "episodeNo"],
        },
      },
      {
        name: "progressSeconds",
        label: "播放进度(秒)",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "totalSeconds",
        label: "总时长(秒)",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "isFinished",
        label: "是否看完",
        type: "switch",
        list: true,
        form: true,
        options: BOOLEAN_OPTIONS,
      },
      {
        name: "lastWatchTime",
        label: "最后观看时间",
        type: "datetime",
        list: true,
        form: false,
      },
      COMMON_FIELDS.createTime,
      COMMON_FIELDS.updateTime,
    ],
  },
  "app-message": {
    key: "app-message",
    title: "消息通知",
    apiPath: "/api/social/messages",
    description: "管理系统通知、业务提醒和站内消息。",
    searchableFields: ["title", "content", "relatedType"],
    fields: [
      COMMON_FIELDS.id,
      {
        name: "senderUserId",
        label: "发送者用户ID",
        type: "select",
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-user",
          labelFields: ["nickname", "username"],
        },
      },
      {
        name: "receiverUserId",
        label: "接收者用户ID",
        type: "select",
        required: true,
        list: true,
        form: true,
        relation: {
          resourceKey: "sys-user",
          labelFields: ["nickname", "username"],
        },
      },
      {
        name: "messageType",
        label: "消息类型",
        type: "select",
        list: true,
        form: true,
        options: MESSAGE_TYPE_OPTIONS,
      },
      {
        name: "title",
        label: "消息标题",
        type: "text",
        required: true,
        list: true,
        form: true,
      },
      {
        name: "content",
        label: "消息内容",
        type: "textarea",
        required: true,
        list: true,
        form: true,
        span: 2,
      },
      {
        name: "relatedType",
        label: "关联业务类型",
        type: "text",
        list: true,
        form: true,
      },
      {
        name: "relatedId",
        label: "关联业务ID",
        type: "number",
        list: true,
        form: true,
      },
      {
        name: "isRead",
        label: "是否已读",
        type: "switch",
        list: true,
        form: true,
        options: BOOLEAN_OPTIONS,
      },
      {
        name: "readTime",
        label: "已读时间",
        type: "datetime",
        list: true,
        form: false,
      },
      {
        name: "sendTime",
        label: "发送时间",
        type: "datetime",
        list: true,
        form: false,
      },
      COMMON_FIELDS.remark,
      COMMON_FIELDS.createTime,
      COMMON_FIELDS.updateTime,
    ],
  },
};

export const menuGroups: MenuGroupConfig[] = [
  {
    title: "总览",
    items: [{ key: "dashboard", label: "仪表盘", icon: "dashboard" }],
  },
  {
    title: "系统管理",
    items: [
      { key: "sys-user", label: "系统用户", icon: "user" },
      { key: "sys-role", label: "角色管理", icon: "team" },
      { key: "sys-permission", label: "权限管理", icon: "safety" },
      { key: "sys-user-role", label: "用户角色", icon: "link" },
      { key: "sys-role-permission", label: "角色权限", icon: "link" },
    ],
  },
  {
    title: "内容管理",
    items: [
      { key: "app-banner", label: "轮播图", icon: "picture" },
      { key: "app-category", label: "内容分类", icon: "appstore" },
      { key: "app-media", label: "内容管理", icon: "video" },
      { key: "app-media-episode", label: "内容分集", icon: "video" },
      { key: "app-media-person-rel", label: "内容人物关联", icon: "relation" },
      { key: "app-person", label: "人物管理", icon: "user" },
    ],
  },
  {
    title: "互动管理",
    items: [
      { key: "app-comment", label: "评论管理", icon: "comment" },
      { key: "app-favorite", label: "收藏记录", icon: "star" },
      { key: "app-follow", label: "关注关系", icon: "share" },
      { key: "app-watch-history", label: "观看历史", icon: "history" },
      { key: "app-message", label: "消息通知", icon: "message" },
    ],
  },
];
